### ISSUE TITLE
[BUG] Default.toml does not have required settings for ups_lite plugin.

### ISSUE THREAD

**Issue by justin-p** [evilsocket/pwnagotchi#1051]
**Describe the bug**
The default.toml currently does not have the required settings for the ups_lite plugin. This will throw the following error if the plugin is enabled and no additional changes are made to the config.toml.

```
Unhandled exception in thread started by <function locked_cb at 0xb651b270>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/__init__.py", line 85, in locked_cb
    cb(*args, *kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/default/ups_lite.py", line 83, in on_ui_update
    if capacity <= self.options['shutdown']:
KeyError: 'shutdown'
```

Manually updating the config.toml with `main.plugins.ups_lite.shutdown = 2` (as it was originally present in the default.yml https://github.com/evilsocket/pwnagotchi/commit/d981b26842ff772215514abc0e01f534b171b557)

Did not test this, but I would expect that the auto shutdown feature that depends on the `shutdown` option is broken when it's not present in either the default.toml or config.toml files.

**To Reproduce**
1. buy ups lite
2. flash clean image
3. perform a normal setup and enable the plugin
4. watch the logs

**Expected behavior**
default.toml should include all the required values for the plugin to function.

**Environment (please complete the following information):**
 - Pwnagotchi version: v1.5.5
 - OS version:
 - Type of hardware: pi0w
 - Any additional hardware used: UPS-Lite

**Comment by justin-p** [comment]
Derek assign: me
