### ISSUE TITLE
[BUG] gpio_buttons

### ISSUE THREAD

**Issue by xenDE** [evilsocket/pwnagotchi#573]
**Describe the bug**
updated 1.2.1 to current master and the gpio_buttons plugin does not work.

error in log:
```
[2019-11-10 18:53:45,093] [ERROR] error while running gpio_buttons.on_loaded : 'list' object has no attribute 'items'
[2019-11-10 18:53:45,100] [ERROR] 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/__init__.py", line 34, in one
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/default/gpio_buttons.py", line 34, in on_loaded
    for gpio, command in gpios.items():
```

**Comment by xenDE** [comment]
needed to change my config and remove "-" before gpio numbers.

```
        gpio_buttons:
            enabled: false
            #The following is a list of the GPIO number for your button, and the command you want to run when it is pressed
            gpios:
              20: 'touch /root/.pwnagotchi-auto && systemctl restart pwnagotchi'
              21: 'shutdown -h now'

```
but now i needed to comment out the two entries in default.yml

so it looks like, the defaults are not cleared if i have other numbers in my config:

```
        gpio_buttons:
            enabled: true
            #The following is a list of the GPIO number for your button, and the command you want to run when it is pressed
            gpios:
              13: 'amixer set Master 3%- ; aplay /etc/pwnagotchi/src-cloned/pwnagotchi-plugin-sound/sound/default/vol.wav'
              26: 'amixer set Master 3%+ ; aplay /etc/pwnagotchi/src-cloned/pwnagotchi-plugin-sound/sound/default/vol.wav'

```

**Comment by xenDE** [comment]
fixed with https://github.com/evilsocket/pwnagotchi/commit/a1746da7f1e28b89ec771bff86abc269f724b1f4#diff-d9ef99ea3dc5a627761667d05380f9f7
