### ISSUE TITLE
Please help this is multiple weeks worth of frustration

### ISSUE THREAD

**Issue by Smurfy37** [evilsocket/pwnagotchi#931]
ive installed rasbian on my raspberry pi i intend on running bettercap locally and using the pixel desktop to run chromium in full screen with the face open but every time i try to launch with sudo pwnagotchi --manual it gives me this error and i cant find diddly squat i feel very stupid please save me

pi@Tony:~ $ sudo pwnagotchi --manual
 [INFO] [update] plugin loaded.
 [INFO] grid plugin loaded.
 [INFO] Session-stats plugin loaded.
 [INFO] [led] plugin loaded for /sys/class/leds/led0/brightness
 [WARNING] ui.fps is 0, the display will only update for major changes
 [INFO] initializing waveshare v2 display
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 131, in <module>
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/display.py", line 72, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/hw/waveshare2.py", line 58, in initialize
    from pwnagotchi.ui.hw.libs.waveshare.v2.waveshare import EPD
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/hw/libs/waveshare/v2/waveshare.py", line 60, in <module>
    SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory
pi@Tony:~ $

i find it especially odd that i dont even have an Eink display attached so it attempting to use a waveshare screen will obviously fail

**Comment by derconno** [comment]
can you post your /etc/pwnagotchi/config.toml?

**Comment by Smurfy37** [comment]
main.name = "Tony"
main.lang = "en"
main.whitelist = [
  "EXAMPLE_NETWORK",
  "ANOTHER_EXAMPLE_NETWORK",
  "fo:od:ba:be:fo:od",
  "fo:od:ba"
]

main.plugins.grid.enabled = true
main.plugins.grid.report = true
main.plugins.grid.exclude = [
  "YourHomeNetworkHere"
]

ui.display.enabled = false
ui.display.type = "inky"
ui.display.color = "black"
----------------------------------------------------

After changing to false i can confirm that it gives me the same error

**Comment by Smurfy37** [comment]
im open to any suggestions

**Comment by Smurfy37** [comment]
ok after some fiddling ive managed to change the error its been trying to go to config.toml and when i checked /usr/local/bin/pwnagotchi    i found  its not looking for that config at all its looking for config.yml so i did a cp to make it that and suddenly its giving me this error ive tried setting ui.display.type to inky and display but neither work giving me the following error

pi@Tony:~ $ sudo pwnagotchi --manual
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 120, in <module>
    config = utils.load_config(args)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/utils.py", line 84, in load_config
    if config['ui']['display']['type'] in ('inky', 'inkyphat'):
TypeError: string indices must be integers

**Comment by Smurfy37** [comment]
the type error would suggest that im not supposed to be entering text into that bit of the config but what numbers would i use as substitute

**Comment by derconno** [comment]
okay, it seems you are using an older version of "pwnagotchi" that relies on .yml config files. Please try to install the current version from [here](https://github.com/evilsocket/pwnagotchi/releases/tag/v1.5.3)

**Comment by Smurfy37** [comment]
thankyou ima try this now 👍

**Comment by Smurfy37** [comment]
pi@Tony:~ $ sudo bettercap -eval "caplets.update; ui.update; quit"
 _          _   _
| |__   ___| |_| |_ ___ _ __ ___ __ _ _ __
| '_ \ / _ \ __| __/ _ \ '__/ __/ _` | '_ \
| |_) |  __/ |_| ||  __/ | | (_| (_| | |_) |
|_.__/ \___|\__|\__\___|_|  \___\__,_| .__/
                                     |_| v1.6.2
http://bettercap.org/



[E] 'Invalid option: -eval', verify your command line arguments executing 'bettercap --help'.


any ideas?

**Comment by Smurfy37** [comment]
ive just realised you dont actually have a link to the pwnagotchi v1.5.3 by itself without raspbian

**Comment by Smurfy37** [comment]
this link is outdated and changing the numbers just downloads a html unless im missing something please call me an idiot if its due XD
![picture](https://user-images.githubusercontent.com/72580496/95620235-c2244c00-0a67-11eb-8c58-3217655af868.PNG)

**Comment by derconno** [comment]
the default raspbian image should work for any pi, so using it could be an option. Also, [this url](https://github.com/evilsocket/pwnagotchi/archive/v1.5.3.zip) can be used to download the current version

**Comment by Smurfy37** [comment]
thanks man i got it working im just stuck on the bettercap working properly now its just constantly waiting for bettercap api to be avaliable

**Comment by Smurfy37** [comment]
i just get this endlessly scrolling


[2020-10-09 21:19:51,861] [INFO] error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/api/session' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) at
     localhost:8081
    </ADDRESS>
  </BODY>
</HTML>
[2020-10-09 21:19:51,862] [INFO] waiting for bettercap API to be available ...
[2020-10-09 21:19:53,337] [INFO] error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/api/session' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) at
     localhost:8081
    </ADDRESS>
  </BODY>
</HTML>
[2020-10-09 21:19:53,338] [INFO] waiting for bettercap API to be available ...
[2020-10-09 21:19:54,347] [INFO] error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/api/session' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) at
     localhost:8081
    </ADDRESS>
  </BODY>
</HTML>
[2020-10-09 21:19:54,347] [INFO] waiting for bettercap API to be available ...
[2020-10-09 21:19:55,362] [INFO] error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/api/session' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) at
     localhost:8081
    </ADDRESS>
  </BODY>
</HTML>
[2020-10-09 21:19:55,363] [INFO] waiting for bettercap API to be available ...
[2020-10-09 21:19:56,488] [INFO] error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/api/session' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) at
     localhost:8081
    </ADDRESS>
  </BODY>
</HTML>
[2020-10-09 21:19:56,489] [INFO] waiting for bettercap API to be available ...
[2020-10-09 21:19:57,649] [INFO] error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Not Found</TITLE></HEAD>
  <BODY>
    <H1>Not Found</H1>
    `/api/session' not found.
    <HR>
    <ADDRESS>
     WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) at
     localhost:8081
    </ADDRESS>
  </BODY>
</HTML>
[2020-10-09 21:19:57,650] [INFO] waiting for bettercap API to be available ...

**Comment by agentages** [comment]
Have you not just flashed the pwnagotchi image to see if that works for you?

**Comment by Smurfy37** [comment]
ive tried that twice and it never worked i just had a blinking _ in the top corner i left it for an hour and it didnt move and ive got a pi4 i feel like im getting close tho i just need to figure out what it means by its not found so bettercap works with pwnagotchi

**Comment by agentages** [comment]
Did you change any passwords or ports in your config?

**Comment by Smurfy37** [comment]
i have not changed the port, the top command doesnt run and the config is the same as im using on my manual pi desktop install ive also wondered if its because im using an led display rather than an E-ink display

**Comment by forceshield** [comment]
Get into a root shell with sudo -i
then try the command
lsof -i :8081

I'm also using an LCD display (240x240 LCDhat)

**Comment by debian-user-france1** [comment]
I would do this:
try again flashing with newest version, CHECK SHASUM! 
or
buy new sd card and try again, I have two raspberry pis, one 3B and one 3B+
